### ISSUE TITLE
most likely due to a circular import

### ISSUE THREAD

**Issue by yang-441** [BrightXiaoHan/optimum-ascend#1]
Installation
`pip install --upgrade-strategy eager install optimum[onnxruntime]`
`python -m pip install git+https://github.com/SmallOneHan/optimum-ascend.git`

执行命令
`optimum-cli export ascend -m moka-ai/m3e-base ./m3e-base-ascend --task feature-extraction --soc-version "Ascend310P3"`

循环依赖，导出模型报错
ImportError: cannot import name 'main_export' from partially initialized module 'optimum.exporters.ascend' (most likely due to a circular import) (/root/anaconda3/envs/whisper_onnx/lib/python3.9/site-packages/optimum/exporters/ascend/__init__.py)

**Comment by BrightXiaoHan** [comment]
抱歉，README上面安装路径写错了（已改正），应该是
```
python -m pip install git+https://github.com/BrightXiaoHan/optimum-ascend.git
```
目前只测试了一些encoder类型的模型，encoder-decoder，decoder类型的模型目前还有点问题。seq2seq分支正在开发。有问题欢迎反馈。
